export default {
  text: '#3c3c3c',
  background: '#f1f1f1',
  btnBg: '#3c3c3c',
  btnBgHero: '#3c3c3c',
  btnText: '#f1f1f1',
  primary: '#3c3c3c',
  secondary: '#f1f1f1',
  accent: '#e9426c',
  lightAccent: '#ffebf0',
  muted: '#eee',
  mutedLight: '#ccc',
  success: '#78b478',
  lightSuccess: '#e6f0e6',
  info: '#b1b1b1',
  warning: '#ffa03c',
  alert: '#e9426c',
  selectBackground: '#eee',
  selectHoverBackground: '#ccc',
  selectArrowColor: '#000',
  checkableBackground: '#fff',
  checkmark: '#000',
  message: '#fff',
  calloutFont: '#fff',
  /*modes: {
    dark: {
      text: '#f1f1f1',
      background: '#3c3c3c',
      btnBg: '#6b6b6c',
      primary: '#f1f1f1',
      secondary: '#3c3c3c',
    },
  },*/
}
